merhaba
Muka6363/Git-GitHub_MK pull request #1
Opened 2022-07-14 09:15 UTC by Gamzeysr

merhaba hocam nihayet işin mantıgını çözdüm kabul ederseniz çok mutlu olurum :)

2022-07-14 11:37 UTC, Muka6363 commented
merhabalar.. acaba neler yaptınız projeme ne tur bır katkıda bulundugunuzu yazar mısınız :))

2022-07-14 11:38 UTC, Muka6363 reviewed
neler yaptıgınızı bı acıklamnızı rıca edıyorum

2022-07-14 11:44 UTC, Muka6363 requested changes
sabahattin alı den bı soz yazın barı :)) oylece yazıp gondermek olmaz...

2022-07-14 11:46 UTC, Gamzeysr commented
hocam ya her mesajınız da tebbessüm ettiriyorsunuz illa sağ olun var olun :D

2022-07-16 05:18 UTC, merged

2022-07-16 08:23 UTC, Gamzeysr commented
hocammm çok detaya girdim isterseniz bi görüşme yapıp anlatabilirim :)